# Generated by Django 4.2 on 2024-09-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_category_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
